# Generated by Django 5.2.17 on 2026-09-22 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, verbose_name='Description / Objectif')),
                ('ai_prompt_template', models.TextField(blank=True, help_text='Instructions/Prompt pour le LLM lors de la génération de messages pour cette campagne.')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'En cours'), ('PAUSED', 'En pause'), ('COMPLETED', 'Terminée')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Entreprise')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='Poste / Titre')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Site Web')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur le prospect ou données collectées.')),
                ('score', models.IntegerField(default=0, help_text="Score de pertinence calculé par l'IA ou règles métier.")),
                ('status', models.CharField(choices=[('NEW', 'Nouveau / Non contacté'), ('GENERATED', "Message généré par l'IA"), ('CONTACTED', 'Contacté'), ('REPLIED', 'A répondu'), ('QUALIFIED', 'Qualifié / Intéressé'), ('UNQUALIFIED', 'Non intéressé'), ('BOUNCED', 'Email Invalide / Erreur')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='prospects.campaign')),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text="Ex: 'SCRAPING_COMPLETED', 'AI_MESSAGE_GENERATED', 'EMAIL_SENT'", max_length=100)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='prospects.campaign')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='prospects.lead')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msg_type', models.CharField(choices=[('EMAIL', 'Email'), ('LINKEDIN', 'Message LinkedIn')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Généré (Brouillon)'), ('QUEUED', "En attente d'envoi"), ('SENT', 'Envoyé'), ('FAILED', "Échec de l'envoi"), ('RECEIVED', 'Réponse reçue du prospect')], default='DRAFT', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('generated_by_ai', models.BooleanField(default=True, verbose_name="Généré par l'IA")),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='prospects.lead')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
