# Generated by Django 5.2.17 on 2026-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unsubscribed',
            field=models.BooleanField(default=False, help_text="Le prospect s'est désinscrit : ne plus lui envoyer de message.", verbose_name='Désinscrit'),
        ),
    ]
