# Generated by Django 5.2.17 on 2026-09-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_lead_unsubscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImapSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailbox_key', models.CharField(help_text='host:username:dossier', max_length=255, unique=True)),
                ('last_uid', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
