# Generated by Django 5.2.17 on 2026-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_imapsyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='followup_delay_days',
            field=models.PositiveIntegerField(default=3, help_text="Nombre de jours sans réponse avant qu'une relance soit générée automatiquement.", verbose_name='Délai avant relance (jours)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_followups',
            field=models.PositiveIntegerField(default=2, help_text='Nombre maximum de relances automatiques générées par prospect.', verbose_name='Nombre max de relances'),
        ),
    ]
