# Generated by Django 5.2.17 on 2026-09-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_campaign_followup_delay_days_campaign_max_followups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='prospects.campaign'),
        ),
    ]
