# Generated by Django 5.2.17 on 2026-09-25 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_alter_lead_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredProspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_place_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, help_text="Terme de recherche utilisé, ex: 'restaurant'", max_length=150)),
                ('search_location', models.CharField(blank=True, help_text='Ville/zone utilisée pour la recherche', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (à compléter manuellement)')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'À qualifier'), ('CONVERTED', 'Converti en prospect'), ('DISCARDED', 'Écarté')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_source', to='prospects.lead')),
            ],
            options={
                'verbose_name': 'Prospect découvert',
                'verbose_name_plural': 'Prospects découverts',
                'ordering': ['-created_at'],
            },
        ),
    ]
