# Generated by Django 5.2.17 on 2026-09-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_discoveredprospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='brevo_message_id',
            field=models.CharField(blank=True, help_text="Identifiant renvoyé par Brevo à l'envoi, utilisé pour recouper les événements du webhook (bounce, spam).", max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Généré (Brouillon)'), ('QUEUED', "En attente d'envoi"), ('SENT', 'Envoyé'), ('FAILED', "Échec de l'envoi"), ('BOUNCED', 'Rejeté par le serveur destinataire'), ('RECEIVED', 'Réponse reçue du prospect')], default='DRAFT', max_length=20),
        ),
    ]
